### ISSUE TITLE
no member named 'runOnFunctions'

### ISSUE THREAD

**Issue by hxm-cpp** [lac-dcc/Daedalus#11]
```
[build] daedalus.cpp:272:27: error: no member named 'runOnFunctions' in 'llvm::MergeFunctionsPass'
[build]   272 |       MergeFunctionsPass::runOnFunctions(outlinedFunctions);
[build]       |       ~~~~~~~~~~~~~~~~~~~~^
[build] 1 error generated.
```

there is problem with the build, i tried LLVM FROM the HEAD 5bb34803a48598c3fa6e480de1814d5fe2d0f652 and LLVM 17

what could be the problem ?

**Comment by Casperento** [comment]
Hey @hxm-cpp,

Our pass relies on a specific fork of LLVM 17.

You can find the repository here: https://github.com/Casperento/llvm-project/tree/merge-functions-pass

At present, LLVM doesn't include the `runOnFunctions` method. We've already submitted a [pull request](https://github.com/llvm/llvm-project/pull/111045) to the official main branch, but it has yet to be reviewed.
